### ISSUE TITLE
Unable to subset radd_date

### ISSUE THREAD

**Issue by karendutko** [eoway/Dja_dispersal_forest_structure#1]
Below I attached the text from the console describing the issue. I used both the methods you suggested but neither worked

![image](https://user-images.githubusercontent.com/85974408/126911880-d9390426-1185-4fe6-a28e-a8cc2a6110dc.png)
> radd<- raster("RADD.tif")
> radd_date <- radd[[2]]
Error in .local(x, ...) : not a valid subset
> radd_date <- radd[2]
> str(radd_date) #use structure function to examine the data type 
 Named num 0
 - attr(*, "names")= chr ""
> dim(radd_date) #rows x columns (in terms pixels) x bands 
NULL
> plot(radd_date)

**Comment by karendutko** [comment]
When I looked at the radd tif file, this is what R produced. It also says the data has one band, which is odd because this is the same file I used in qgis![image](https://user-images.githubusercontent.com/85974408/126912569-d588e5ff-fa02-47af-b9f2-25d30cceb4d1.png)> str(radd) #use structure function to examine the data type 
Formal class 'RasterLayer' [package "raster"] with 12 slots
  ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. ..@ name        : chr "/Users/karendutko/Downloads/NASA products/RADD.tif"
  .. .. ..@ datanotation: chr "INT2S"
  .. .. ..@ byteorder   : chr "little"
  .. .. ..@ nodatavalue : num -Inf
  .. .. ..@ NAchanged   : logi FALSE
  .. .. ..@ nbands      : int 2
  .. .. ..@ bandorder   : chr "BIL"
  .. .. ..@ offset      : int 0
  .. .. ..@ toptobottom : logi TRUE
  .. .. ..@ blockrows   : int 256
  .. .. ..@ blockcols   : int 256
  .. .. ..@ driver      : chr "gdal"
  .. .. ..@ open        : logi FALSE
  ..@ data    :Formal class '.SingleLayerData' [package "raster"] with 13 slots
  .. .. ..@ values    : logi(0) 
  .. .. ..@ offset    : num 0
  .. .. ..@ gain      : num 1
  .. .. ..@ inmemory  : logi FALSE
  .. .. ..@ fromdisk  : logi TRUE
  .. .. ..@ isfactor  : logi FALSE
  .. .. ..@ attributes: list()
  .. .. ..@ haveminmax: logi TRUE
  .. .. ..@ min       : num -32768
  .. .. ..@ max       : num 32767
  .. .. ..@ band      : int 1
  .. .. ..@ unit      : chr ""
  .. .. ..@ names     : chr "RADD"
  ..@ legend  :Formal class '.RasterLegend' [package "raster"] with 5 slots
  .. .. ..@ type      : chr(0) 
  .. .. ..@ values    : logi(0) 
  .. .. ..@ color     : logi(0) 
  .. .. ..@ names     : logi(0) 
  .. .. ..@ colortable: logi(0) 
  ..@ title   : chr(0) 
  ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. ..@ xmin: num 9.72
  .. .. ..@ xmax: num 16.3
  .. .. ..@ ymin: num 0.11
  .. .. ..@ ymax: num 6.16
  ..@ rotated : logi FALSE
  ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. ..@ geotrans: num(0) 
  .. .. ..@ transfun:function ()  
  ..@ ncols   : int 24349
  ..@ nrows   : int 22440
  ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. ..@ projargs: chr "+proj=longlat +datum=WGS84 +no_defs"
  ..@ history : list()
  ..@ z       : list()
> dim(radd) #rows x columns (in terms pixels) x bands 
[1] 22440 24349     1
> plot(radd)

**Comment by eoway** [comment]
The raster() function will load a raster file, but only the first band. Use the brick() function to download a file that has multiple bands. 

Use the code below: 

radd <- brick("RADD.tif")
radd_date <- radd[[2]]
radd_date <- radd$Date # Just an alternative approach to doing the exact same thing as the previous line. 
str(radd_date) #use structure function to examine the data type
