### ISSUE TITLE
Cannot convert to data frame

### ISSUE THREAD

**Issue by karendutko** [eoway/Dja_dispersal_forest_structure#2]
I am receiving this issue when I try to convert the datasets to data frames

> datamask_df <- as.data.frame(hansen_datamask, xy=T)
Error: vector memory exhausted (limit reached?)

**Comment by eoway** [comment]
It looks like this is a memory limitation error. This is where it will come in handy to start using the virtual desktops. It's common to run into issues when working with large datasets like this one on personal laptops. It runs successfully on my computer, but does take a few minutes. 

Try running it on the virtual desktop and let me know how it goes.
