### ISSUE TITLE
ggplot2 on remote computer issue

### ISSUE THREAD

**Issue by karendutko** [eoway/Dja_dispersal_forest_structure#3]
I am unable to install and run ggplot2 on the remote desktop without installing Rtools (I do not have this issue on my personal laptop). I also cannot install Rtools because I do not have the passcode for the remote desktop to approve changes. I believe based on my research the ggplot function is necessary in order to plot dataframes with multiple columns and set a column on the y axis, and since we are looking at the total deforestation I made the dataframe have two columns (year and frequency*30/1000 to get sq km of degradation per given year). I am stuck on this issue and would love to hear suggestions on how to set the second column on the y axis without the ggplot function. I will keep you updated as I try to figure this out.

**Comment by karendutko** [comment]
I created a test run with the dataset "new_df_samp" which featured the deforestation total in square kilometers along with the year. This is the result:![image](https://user-images.githubusercontent.com/85974408/129511610-df33c515-72ae-40ee-ac80-2a5a8d4d6353.png)test <- read.csv("new_df_samp.csv")
> ggplot(test, aes(Year, Deforestation_total)) + geom_bar(stat = "identity")

However, when I used the same code with the updated "hansen" dataset (uploaded on box), I cannot get a barchart and instead I only get this message:
> ggplot(hansen, aes(Year, Deforestation_total)) + geom_bar(stat = "identity")

Warning message:
Removed 1 rows containing missing values (position_stack). 

It seems that there was no actual error, but the computer probably couldn't fully process the data

**Comment by eoway** [comment]
The plot looks great. The warning message refers to one row from the dataset being removed due to no data values for what you're plotting. Let's look at the ggplot installation error together today during our meeting.
